Repository RE-V-UP/v-up-ver2, pull requests merged in 2024-04, with the labels that each got.

#5 Refactor(#1):불필요한 코드 정리, 파일 삭제
  src/components/mypage/Pagination.tsx
  src/components/mypage/WriteList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/search/MusicSearch.tsx
  src/components/search/MusicSearchModal.tsx
  src/components/search/NoSearchResultItem.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/WriteList.tsx
  src/query/musicPlayer/musicPlayerQueryKey.ts
  src/query/musicPlayer/musicPlayerQueryKeys.ts
  src/query/mutation.ts
  src/query/queryKey.ts
  src/query/user/userQueryKeys.ts
Labels: documentation

#9 Refactor(#8) : 마이페이지, 유저페이지 쿼리키 공통 쿼리키로 변경, 유저 정보 쿼리키 관리 파일 생성 / Style : 페이지네이션 여백 수정
  src/components/mypage/FollowerList.tsx
  src/components/mypage/FollowingList.tsx
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/mypage/WriteList.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/UserInfo.tsx
  src/components/userpage/UserPlaylist.tsx
  src/components/userpage/WriteList.tsx
  src/query/user/userQueryKeys.ts
  src/util/Pagination .tsx
Labels: documentation

#15 Feat(#14):드래그 앤 드롭
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/components/main/GenreMusicItem.tsx
  src/components/player/AudioCss.css
  src/components/player/CurrentMusicList.tsx
  src/components/player/Player.tsx
  src/components/search/NoSearchResultItem.tsx
  src/components/search/SearchedMusicData.tsx
  src/query/community/communityQueryKey.ts
  src/query/search/searchQueryKeys.ts
  src/shared/musicPlayer/api.ts
  src/shared/search/api.ts
  src/shared/store/playerStore.ts
  src/types/musicPlayer/types.ts
  src/util/util.ts
Labels: enhancement

#17 Feat(#16) : 마이 플레이리스트 무한스크롤 기능 작업
  src/components/mypage/MyPlaylist.tsx
  src/shared/mypage/api.ts
  src/util/useIntersectionObserver.ts
Labels: documentation, enhancement

#22 Fix(#21) : 마이페이지 정보 수정 에러 처리
  src/components/mypage/MyInfo.tsx
  src/shared/mypage/api.ts
Labels: bug

#24 Fix(#23) : 커뮤니티 등록 페이지 - 퀼 에디터 빌드 오류 해결
  package.json
  src/components/communityDetail/CommunityAddMusic.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/CommunityQuillEditor.tsx
  src/components/communityDetail/QuillEditor.tsx
  src/components/communityDetail/value.ts
  src/query/communityDetail/mutation.ts
  src/query/communityDetail/queryKey.ts
  src/types/communityDetail/detailTypes.ts
  yarn.lock
Labels: bug, documentation, enhancement

#27 Fix(#26) : 커뮤니티 등록 페이지 - 퀼 에디터 컴포넌트 수정 및 분리
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/CommunityNoSsrQuillEditor.tsx
  src/components/communityDetail/CommunityQuillEditor.tsx
  src/components/communityDetail/value.ts
Labels: documentation, enhancement

#30 Fix(#26) : 커뮤니티 등록 페이지 - 퀼 에디터 조회되는 영역 버그 해결 및 컴포넌트 수정
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityNoSsrQuillEditor.tsx
  src/components/communityDetail/CommunityQuillEditor.tsx
  src/components/communityDetail/QuillEditor.tsx
Labels: bug, documentation, enhancement

#35 Style(#34) : 레이아웃 수정
  src/components/common/Container.tsx
Labels: style

#36 Feat(#33) : 커뮤니티 등록, 상세 페이지 - 음악 검색 목록 제외, 음악 정보에 드래그앤드롭 연결
  public/images/loadingBar.gif
  src/components/communityDetail/CommunityAddMusic.tsx
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/CommunityCreate.tsx
  src/components/communityDetail/value.ts
  src/components/search/MusicSearchModal.tsx
  src/shared/communitydetail/detailApi.ts
  src/types/communityDetail/detailTypes.ts
Labels: documentation, enhancement

#39 Feat(#38),Fix(#31) : 업데이트 된 로그인 로직 병합, 커뮤니티 상세 페이지 - DB likeCount필드 컬럼에 들어갈 값 로직 구성
  src/app/api/auth/[...nextauth]/route.ts
  src/components/communityDetail/LikeButton.tsx
  src/components/findpassword/FindPassword.tsx
  src/components/join/Join.tsx
  src/components/join/value.ts
  src/components/login/Login.tsx
  src/shared/communitydetail/detailApi.ts
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
  src/types/supabase.ts
Labels: documentation, enhancement

#46 Release(#45) : 배포
  src/app/api/auth/[...nextauth]/route.ts
  src/components/communityDetail/LikeButton.tsx
  src/components/findpassword/FindPassword.tsx
  src/components/join/Join.tsx
  src/components/join/value.ts
  src/components/login/Login.tsx
  src/shared/communitydetail/detailApi.ts
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
  src/types/supabase.ts
Labels: documentation, enhancement

#47 Feat(#19):플레이리스트 전체 선택, 커뮤니티 좋아요 정렬 오류 수정
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/components/communityList/CommunityListData.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/player/AudioCss.css
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Player.tsx
  src/components/search/GenreMusicRecommendations.tsx
  src/components/search/GenreRandomMusic.tsx
  src/components/search/NoSearchResult.tsx
  src/components/search/NoSearchResultItem.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/shared/community/api.ts
  src/shared/main/api.ts
  src/shared/musicPlayer/api.ts
  src/types/musicPlayer/types.ts
  src/util/util.ts
Labels: bug, enhancement, style

#54 Refactor(#52) : 퍼스널 페이지 쿼리키 분리, 공통 쿼리키 사용 및 주석제거 / Refactor(#53) : 퍼스널 페이지 뮤테이션 분리 / Style : 퍼스널 뮤직 진단 수정
  src/components/personal/GenderPage.tsx
  src/components/personal/PersonalRecommend.tsx
  src/components/personal/PersonalSubTest.tsx
  src/components/personal/ResultChart.tsx
  src/query/personal/keys.constant.ts
  src/query/personal/personalMutation.ts
  src/query/personal/personalQueryKey.ts
  src/query/personal/useMutationPersonal.ts
  src/query/personal/useQueryPersonal.ts
  src/shared/personal/personalApi.ts
Labels: documentation, enhancement, style

#56 Style(#55) : 포인트 라벨 폰트 사이즈 수정
  src/components/personal/ResultChart.tsx
Labels: style

#63 feat(#61) : 퍼스널 뮤직 진단 음악 랜덤으로 추천하기 / fix(#62) : 오늘은 그만보기 모달 수정
  src/components/personal/PersonalModal.tsx
  src/shared/personal/personalApi.ts
Labels: bug, enhancement

#65 Feat(#58) : 서비스 소개 페이지 모달 생성 / Style(#64) : 이용가이드 스크롤 추가
  src/components/common/Container.tsx
  src/components/service/Service.tsx
  src/components/service/ServiceModal.tsx
  src/components/service/ServiecModalTest.tsx
Labels: documentation, style

#60 Feat(#14) 현재 플레이리스트 드래그로 순서 변경, 로컬스토리지에 저장 완료
  public/images/musicDragIcon.svg
  src/app/(nonAuth)/search/page.tsx
  src/components/communityList/CommunityListData.tsx
  src/components/player/CurrentMusicList.tsx
  src/components/player/MusicPlayer.tsx
  src/components/player/Player.tsx
  src/components/search/GenreMusicRecommendations.tsx
  src/components/search/GenreRandomMusic.tsx
  src/components/search/NoSearchResultItem.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/hooks/hooks.ts
  src/shared/musicPlayer/api.ts
  src/shared/store/playerStore.ts
  src/shared/store/searchStore.ts
  src/types/musicPlayer/types.ts
  src/types/supabase.ts
  src/util/Pagination .tsx
Labels: enhancement

#66 Feat(#28) : 양방향 무한 스크롤 기능 추가
  src/components/main/MainBanner.tsx
  src/components/mypage/MyPlaylist.tsx
  src/components/userpage/UserPlaylist.tsx
  src/shared/main/api.ts
  src/shared/mypage/api.ts
  src/shared/userpage/api.ts
  src/util/InfiniteScrollContainer.tsx
  src/util/useIntersectionObserver.ts
Labels: documentation, enhancement

#68 Fix(#67) : 팔로우리스트 에러 처리
  src/components/mypage/FollowerList.tsx
  src/components/mypage/MyInfo.tsx
  src/shared/mypage/api.ts
Labels: bug

#70 Feat,Fix(#69) : 커뮤니티 상세 페이지 - 다른 페이지 이동할 때 이전 페이지가 잠시 보였던 현상 해결
  src/components/communityDetail/CommunityContents.tsx
  src/components/communityDetail/ContentsHeader.tsx
  src/components/communityDetail/LikeButton.tsx
  src/query/communityDetail/queryKey.ts
  src/shared/communitydetail/detailApi.ts
Labels: bug, documentation, enhancement

#72 Style(#71) : 이용가이드 내용수정 및 디자인 변경
  public/images/XIcon.png
  public/images/cdIcon.svg
  src/components/Header.tsx
  src/components/service/Service.tsx
  src/components/service/ServiceModal.tsx
Labels: style

#74 Style(#73) : 모달 크기 수정 및 퍼스널 뮤직 진단 안내 추가
  public/images/personalHeart.svg
  src/components/service/ServiceModal.tsx
Labels: style

#76 Fix(#75) : 쿼리키 변경 - 커뮤니티 게시글 수정 새로고침 이슈 생긴점 해결
  src/components/communityDetail/CommunityContents.tsx
  src/query/communityDetail/mutation.ts
Labels: bug, documentation, enhancement

#79 Fix(#78):검색 후 이젠 페이지 검색 안되는 오류 수정 완료
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/components/mypage/LikeBoardList.tsx
  src/components/mypage/WriteList.tsx
  src/components/search/GenreMusicRecommendations.tsx
  src/components/search/GenreRandomMusic.tsx
  src/components/search/MusicSearchModal.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/components/userpage/LikeBoardList.tsx
  src/components/userpage/WriteList.tsx
  src/query/search/searchQueryKeys.ts
  src/shared/store/paginationStore.ts
  src/shared/store/searchStore.ts
  src/util/Pagination .tsx
  src/util/util.ts
Labels: bug, documentation

#81 Fix:서버 랜덤에서 클라이언트 랜덤으로 수정
  src/app/(nonAuth)/community/page.tsx
  src/components/main/RandomMusicList.tsx
  src/components/player/playerIcons/MyLoopIcon.tsx
  src/components/player/playerIcons/MyLoopOffIcon.tsx
  src/components/player/playerIcons/MyNextIcon.tsx
  src/components/player/playerIcons/MyPauseIcon.tsx
  src/components/player/playerIcons/MyPlayIcon.tsx
  src/components/player/playerIcons/MyPreviousIcon.tsx
  src/components/player/playerIcons/ProgressContainer.tsx
  src/components/search/GenreRandomMusic.tsx
  src/shared/main/api.ts
Labels: bug

#85 Feat(#83) : 무한 스크롤 쓰로틀링 적용
  package.json
  src/components/mypage/MyPlaylist.tsx
  src/components/userpage/UserPlaylist.tsx
  yarn.lock
Labels: documentation, enhancement
